<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hogwarts [
    <!ELEMENT hogwarts (rooms,teachers,courses)>
    <!ELEMENT rooms (room+)>
    <!ATTLIST room name ID #REQUIRED>
    <!ATTLIST room  nrSeats NMTOKEN #REQUIRED>
    <!ELEMENT room EMPTY>
    <!ELEMENT teachers (teacher+)>
    <!ATTLIST teacher  name ID #REQUIRED>
    <!ATTLIST teacher room IDREF #REQUIRED>
    <!ELEMENT teacher (title?)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT courses (course+)>
    <!ATTLIST course name  ID #REQUIRED>
    <!ATTLIST course teache IDREF #REQUIRED>
    <!ATTLIST course nrStudents NMTOKEN #Implied>
    <!ELEMENT course (class+)>
    <!ELEMENT class (#PCDATA)>
    <!ATTLIST class day NMTOKEM #REQUIRED>
    <!ATTLIST class hour NMTOKEN #REQUIRED>
]>
<hogwarts>
    <rooms>
        <room name="The_Dungeon" nrSeats="34"/>
     <room name="The_Cabin" nrSeats="163"/>
    </rooms>
    <teachers>
         <teacher name="Snape" room="The_Dungeon">
         <title>Professor</title>
    </teacher>
        <teacher name="Hagrid" room="The_Cabin"/>
    </teachers>
    <courses>
     <course name="Potioncraft" teacher="Snape" nrStudents="28">
        <class day="Monday" hour="10"/>
    </course>
    <course name="Handling_of_Wild_Creatures" teacher="Hagrid">
     <class day="Saturday" hour="13"/>
     <class day="Thursday" hour="7"/>
    </course>
    </courses>
    </hogwarts>