=== jglgap/xmlVALIDATING/ex13.dtd
<!ELEMENT bookDatabase (book+)>
<!ATTLIST book bookID ID #REQUIRED>
<!ELEMENT book (author+,image?,content+,newchapters*)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT content (chapter,description)>
<!ATTLIST chapter number NMTOKEN #REQUIRED>
<!ELEMENT chapter (#PCDATA)>
<!ELEMENT description (section*,summary?)>
<!ELEMENT section (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT newchapters (chapter,description)>

=== jglgap/xmlVALIDATING/dtd/ex13.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE bookDatabase SYSTEM "ex13.dtd">
<bookDatabase>
    <book bookID="ISBN-0-13-xxx">
        <author>Elliotte Rusty Harold</author>
        <content>
            <chapter number="1">XML Structure, Syntax</chapter>
            <description>
              <section>XML Fundamentals</section>
            </description>
        </content>
        <content>
            <chapter number="2">Document Type Definitions</chapter>
            <description>
                <section>Element Declarations</section>
                <section>Attributes Declarations</section>
                <summary>summary of the chapter 2</summary>
            </description>
        </content>
    </book>
    <book bookID="ISBN-0-586-xxx">
        <author>Ian Foster</author>
        <author>Carl Kesselman</author>
        <image>grid architecture</image>
        <content>
            <chapter number="1">Grids in Context</chapter>
             <description/>
         </content>
        <newchapters>
             <chapter number="20">Network structure</chapter>
             <description>
                <section>The Future(1998-2005)</section>
             </description>
        </newchapters>
    </book>
    </bookDatabase>
