<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE parent [
    <!ELEMENT parent (son*,daughter+)>
    <!ELEMENT son (#PCDATA)>
    <!ELEMENT daughter (#PCDATA)>
]>
<parent>
    <son>Anxo</son>
    <son>TETE</son>
    <daughter>Nerea</daughter>
    <daughter>Noria</daughter>
    <daughter>mona</daughter>
    </parent>