<?xml version="1.0"?>	
<!DOCTYPE stock[	
<!ELEMENT stock (new-car|used-car)*>	<!-- Pode ser used o new-->
<!ELEMENT new-car (model,price)>	
<!ELEMENT used-car (model,price,mileage,condition?)>	
<!ELEMENT model (#PCDATA)>	
<!ELEMENT price (#PCDATA)>	
<!ELEMENT mileage (#PCDATA)>	
<!ELEMENT condition (#PCDATA)>	
]>
<stock>
    <new-car>
        <model>RAV4</model>
        <price>30000â‚¬</price>
    </new-car>
    <used-car>
        <model>Leon</model>
        <price>4000</price>
        <mileage>175002</mileage>
        <condition>Pretty Good</condition>
    </used-car>
</stock>