=== jglgap/xmlVALIDATING/xsd/X.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="photo" type="xs:string"/>
                            <xs:element name="tags" type="xs:string"/>
                            <xs:element name="diameter" type="numeric" />
                            <xs:element name="price" type="numeric"/>
                            <xs:element name="weigth" type="numeric"/>
                            <xs:element name="enumeration" type="numeric"/>
                            <xs:element name="size" minOccurs="0">
                                <xs:simpleType  >
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(big|small|empty)"></xs:pattern>                                   
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="numeric">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:totalDigits value="6"/>
            <xs:fractionDigits value="2"/>
            <xs:pattern value="[0-9]{1,4}.[0-9]{1,2}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jglgap/xmlVALIDATING/xsd/X.XML
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="X.xsd">
    <item>
        <name>qe</name>
        <photo>qe</photo>
        <tags>qe</tags>
        <diameter>4.2</diameter>
        <price>4.2</price>
        <weigth>4.2</weigth>
        <enumeration>4.2</enumeration>
        <size>big</size>
    </item>
    <item>
        <name></name>
        <photo></photo>
        <tags></tags>
        <diameter>4.2</diameter>
        <price>4.2</price>
        <weigth>4.2</weigth>
        <enumeration>4.2</enumeration>
    </item>
</items>
